name: Show me the secrets
on: 
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        GPLAY_KEY: ${{ secrets.GPLAY_SERVICE_ACCOUNT_JSON_KEY }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        echo $KEYSTORE >> secrets.txt
        echo $KEYSTORE_PASSWORD >> secrets.txt
        echo $KEY_ALIAS >> secrets.txt
        echo $GPLAY_KEY >> secrets.txt
        echo $KEY_PASSWORD >> secrets.txt        

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
